[package]
name = "gm8emulator"
version = "0.1.0"
authors = ["Adamcake", "viri"]
license = "GPL-2.0-only"
edition = "2018"

[build-dependencies]
gl_generator = "0.14.0"

[dependencies]
getopts = "0.2.21"
glfw = { git = "https://github.com/bjz/glfw-rs.git" }
gm8exe = { git = "https://github.com/OpenGM8/GM8Decompiler.git" }
memoffset = "0.5.3"
png = "0.15.2"
rand = "0.7.2" # for seeding, not generating
rect_packer = "0.2.1"
rmp3 = "0.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
